[package]
name = "scpi-tool"
version = "0.1.1"
edition = "2024"
description = "Command line tool for executing SCPI queries and gathering responses."

[dependencies]
clap = { version = "4.6.4", features = ["derive"] }
env_logger = "0.11.11"
log = "0.4.33"
regex = "1.13.1"
rustyline = "18.0.1"
serialport = "4.9.0"
